package com.igoda.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.igoda.dao.entity.MattingImage;

import com.igoda.dao.MattingImageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mattingImageDaoConfig;

    private final MattingImageDao mattingImageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mattingImageDaoConfig = daoConfigMap.get(MattingImageDao.class).clone();
        mattingImageDaoConfig.initIdentityScope(type);

        mattingImageDao = new MattingImageDao(mattingImageDaoConfig, this);

        registerDao(MattingImage.class, mattingImageDao);
    }
    
    public void clear() {
        mattingImageDaoConfig.clearIdentityScope();
    }

    public MattingImageDao getMattingImageDao() {
        return mattingImageDao;
    }

}
